#!/bin/bash

picom -b &
numlockx &
pactl set-default-sink alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1
nm-applet &
# volumeicon &
# blueman-applet &
dunst &
nitrogen --restore &
tint2 &
xcape -e 'Super_L=Super_L|E' &
udiskie -2
qjoypad &

# Start e-macs on my TODO list
# sleep 3 && emacs -fs ~/Documents/org/notes.org &
